apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-deploy
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.labels }}
  template:
    metadata:
      labels:
        app: {{ .Values.labels }}
    spec:
      containers:
      - name: myapp
        image: {{ .Values.image }}
        ports:
        - containerPort: 8080
        env:
        - name: IMAGE_NAME
          value: {{ .Values.image | quote }}
        resources:
          requests:
            memory: {{ .Values.requests.memory}}
            cpu: {{ .Values.requests.cpu}}
          limits:
            memory: {{ .Values.limits.memory}}
            cpu: {{ .Values.limits.cpu}}
